datatables:
  jshead: js/jquery.dataTables.min.js
  css: css/jquery.dataTables.css
  cdn:
    jshead:
      - "https://cdn.datatables.net/s/bs-3.3.5/jq-2.1.4,dt-1.10.10,b-1.1.0,b-colvis-1.1.0,fh-3.1.0,r-2.0.0,sc-1.4.0/datatables.min.js"
    css:
      - "https://cdn.datatables.net/s/bs-3.3.5/jq-2.1.4,dt-1.10.10,b-1.1.0,b-colvis-1.1.0,fh-3.1.0,r-2.0.0,sc-1.4.0/datatables.min.css"
